- name: Appliance K8s
  hosts: all
  vars_files:
    - ../secrets.d/secrets.ansible-vars.yml
    - ../conf/appliance.common.ansible-vars.yml
  tasks: 
    - name: Install k8s dependencies
      include_role:
        name: geerlingguy.kubernetes        

    - name: Download rancher cli
      file: state=link src={{appliance_setup_path}}/bin/crancher dest=/usr/bin/rancher mode=a+x force=yes  
