- name: Install Powershell
  hosts: all
  vars_files:
    - ../conf/appliance.secrets.ansible-vars.yml
    - ../conf/appliance.common.ansible-vars.yml
  tasks:

    - name: Download packages-microsoft-prod.deb.
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb

    - name: Run packages-microsoft-prod.deb file to add to source list.
      command: dpkg -i /tmp/packages-microsoft-prod.deb

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes

    - name: Install powershell
      apt:
        name: powershell
        state: present
