---
- name: Appliance Samba
  hosts: all
  vars_files:
    - ../conf/appliance.secrets.ansible-vars.yml
    - ../conf/appliance.common.ansible-vars.yml
    
  roles:
    - bertvv.samba

  post_tasks:
    - name: Open Samba ports
      ufw: >
        rule=allow
        port={{ item }}
        proto=tcp
      with_items:
        - 139
        - 445
        